site_name: My Odoo Documentation
nav:
  - Home: index.md
  - Setup:
    - Setting Up Odoo with Docker: setup/install.md
    - First-Time Setup: setup/firsttimeuse.md
    - Visual Studio Code Integration: setup/vscsetup.md
  - Add-ons and Modules:
    - Introduction to Add-ons and Modules: addons/intro.md
    - Creating (Scaffolding) an Add-on: addons/scaffolding.md
    - Models: addons/models.md
